### ISSUE TITLE
Not pushed to Docker Hub

### ISSUE THREAD

**Issue by inolen** [multiarch/fedora#2]
It looks like the current configurations are no longer being pushed to Docker Hub:
https://hub.docker.com/r/multiarch/fedora/tags/

**Comment by moul** [comment]
Done, can you try again?

**Comment by junaruga** [comment]
@inolen Now this repository has a pipeline to push to DockerHub in `.travis.yml`, and the latest Fedora 29 and 30 's multiarch containers were uploaded.
https://github.com/multiarch/fedora/blob/master/.travis.yml#L43-L46
https://hub.docker.com/r/multiarch/fedora/tags

Can you check it?
Maybe we can close this ticket.

**Comment by junaruga** [comment]
@inolen I think this was solved. If you still have an issue, you can reopen.
Thanks!
