### ISSUE TITLE
Uploading Fedora 29, 30 images to DockerHub

### ISSUE THREAD

**Issue by junaruga** [multiarch/fedora#8]
This ticket is just for a task.
Please remember to upload the latest container images of Fedora 29 and 30 to DockerHub setting `DOCKER_USERNAME` and `DOCKER_PASSWORD` in Travis Setting page.
https://hub.docker.com/r/multiarch/fedora/tags/

Once you upload it to DockerHub, close this ticket.

Thank you.

**Comment by junaruga** [comment]
Right now `after_success` is like this.

https://travis-ci.org/multiarch/fedora/jobs/528572365

```
0.36s$ if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
        docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" "$DOCKER_SERVER" && \
            docker push $DOCKER_REPO
    fi
    
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
Done. Your build exited with 0.
```

Until it will be uploaded, people can use my repository as temporary workflow.

https://quay.io/repository/junaruga/multiarch-fedora

```
$ docker run --rm --privileged multiarch/qemu-user-static:register --reset

$ docker run --rm -t quay.io/junaruga/multiarch-fedora:30-aarch64 uname -m
aarch64
```

**Comment by lafin** [comment]
@moul And will be fine if you give access @junaruga to the @multiarch he doing the right things.

**Comment by junaruga** [comment]
I am happy to become a member of multiarch.

**Comment by junaruga** [comment]
@lafin , can you contact @moul by email or something?
I think he is busy seeing his GitHub page. he might not notice this ticket.
Or can you set `DOCKER_USERNAME` and `DOCKER_PASSWORD` to this repository's Travis setting then run Travis?

**Comment by lafin** [comment]
I emailed today already on the just one email address which I know, but not get answered yet. About `DOCKER_USERNAME` If I could do this, I would do it. Sorry.

**Comment by junaruga** [comment]
@lafin sure, thank you!

**Comment by moul** [comment]
@junaruga you are now a member of the organization, thank you! :)

**Comment by moul** [comment]
env vars are configured on Travis, can you give a new try?

**Comment by junaruga** [comment]
@moul now I became the member. thank you!
But it seems that I do not have a permission to run Travis for this repository.
I tried to restart current master branch's Travis build.
https://travis-ci.org/multiarch/fedora

Did you intended it?

**Comment by junaruga** [comment]
Sorry, my mistake. now I also have a permission to run the Travis multiarch/fedora.

**Comment by junaruga** [comment]
@lafin I think you can have a permission to run the Travis.
Can you see "Multiarch" in the left side menu of below page?
https://travis-ci.org/account/repositories

If you do not have, click below test's link on the page, to add organization, then you will see you can run the Travis for multiarch.
> Missing an organization?
> Review and add your authorized organizations.

**Comment by junaruga** [comment]
Thank you! Now successfully uploaded to the DockerHub.
https://hub.docker.com/r/multiarch/fedora/tags

```
$ uname -m
x86_64
$ docker run --rm --privileged multiarch/qemu-user-static:register --reset

$ docker run --rm -t multiarch/fedora:29-aarch64 uname -m
aarch64
$ docker run --rm -t multiarch/fedora:29-ppc64le uname -m
ppc64le
$ docker run --rm -t multiarch/fedora:29-s390x uname -m
s390x

$ docker run --rm -t multiarch/fedora:30-aarch64 uname -m
aarch64
$ docker run --rm -t multiarch/fedora:30-s390x uname -m
s390x
```
